### ISSUE TITLE
List is always empty

### ISSUE THREAD

**Issue by DerVolli** [in2code-de/publications#1]
We tried the plugin on the website of the University of Passau. It was easily to do to import the data of the old sevenpack plugin - but when we want to see the list of the publications in the frontend it is empty. There is always the error message ("No publications found").

For us it did not work to install it via composer therefore we installed the plugin from the TER and merged the renanbr bibtex parser.

Please help ;)

**Comment by einpraegsam** [comment]
Hi,

that sounds a bit strange. What if you just create a new page with a new publications plugin without any settings (and two or three records before)? Every filtersetting in the plugin will reduce the possible amount of records of course. If you are using the filter in frontend, an anonymous cookie is set with your filter settings. This can be deleted by clicking the "remove filter" button.

If you don't install the extension via composer (why did it not work?), the import via backend module will not work by default.

If you have any further questions, please don't hesitate and ask.

Alex

**Comment by kfumy** [comment]
Hey,

did you choose a sys Folder (where your publications are stored) in the Plugin?

**Comment by DerVolli** [comment]
That is just what I did: I created an empty plugin and chose the page (not a sys folder - does this really make a difference?) where the publications were imported. Yet nothing was shown.Installing by composer did for one not work because we have a different folder structure. When I run "composer require in2code/publications" in an empty folder I get a vendor and a public folder. But the vendor folder lives inside the typo3 core and the public folder lives in another place. We also don't understand why a complete typo3 installation is downloaded when we run that command.I also tried to run the composer command in the typo3 root folder which also did not work because I got a lot of error messages.

    Am Mittwoch, 16. Oktober 2019, 11:07:26 MESZ hat kfumy <notifications@github.com> Folgendes geschrieben:  
 
 
Hey,

did you choose a sys Folder (where your publications are stored) in the Plugin?

**Comment by einpraegsam** [comment]
Ok, if you install a TYPO3 extension via composer, of course all requirements are also installed and this is the TYPO3 core at minimum. A public folder should handle the DocumentRoot while packages are stored into a vendor folder outside the DocumentRoot for security reasons. If a vendor has known security problems, there is no change to call the php-script via Apache.

Nevertheless back to a non-composer installation: I try to understand where the problem came from. Because I can't debug on your system, can you please do this step by step and give me feedback:
1) Install publications in your TYPO3
2) Clean caches in Install Tool, Make a DB-compare, Build the autoload-files
3) Add a sysfolder anywhere in your pagetree
4) Add one (or) more publication test-records by hand
5) Add a normal page with a publication plugin with empty configuration
6) Add the static TypoScript template of publications to your root template
7) View the normal page in frontend
8) Is it still "No publications found"?

**Comment by DerVolli** [comment]
Done so, still no publications found, sorry.    Am Donnerstag, 17. Oktober 2019, 09:26:48 MESZ hat Alex Kellner <notifications@github.com> Folgendes geschrieben:  
 
 
Ok, if you install a TYPO3 extension via composer, of course all requirements are also installed and this is the TYPO3 core at minimum. A public folder should handle the DocumentRoot while packages are stored into a vendor folder outside the DocumentRoot for security reasons. If a vendor has known security problems, there is no change to call the php-script via Apache.

Nevertheless back to a non-composer installation: I try to understand where the problem came from. Because I can't debug on your system, can you please do this step by step and give me feedback:
   
   - Install publications in your TYPO3
   - Clean caches in Install Tool, Make a DB-compare, Build the autoload-files
   - Add a sysfolder anywhere in your pagetree
   - Add one (or) more publication test-records by hand
   - Add a normal page with a publication plugin with empty configuration
   - Add the static TypoScript template of publications to your root template
   - View the normal page in frontend
   - Is it still "No publications found"?

**Comment by einpraegsam** [comment]
Ok, so I'm out now without debugging - sorry, no ideas left.
Probably it's because of the classic-mode (non composer) even if I can't imagine this.

**Comment by einpraegsam** [comment]
We have to close old issues to be able to not lose overview over the open issues.
Sorry, but at the moment I would say it's not possible to use publications without a modern composer setup.
